### ISSUE TITLE
Nested resource cannot be json-ized

### ISSUE THREAD

**Issue by Pittiplatsch** [blongden/hal#49] opened 2015-07-22 16:32 UTC
Nested resources which contain only one sub resource cannot be rendered as json.

Testing with only ONE line uncommented:

```
$hal = new \Nocarrier\Hal();
// following options do NOT work
// $hal->setResource(
//     'foo',
//     (new \Nocarrier\Hal())
//         ->setResource('bar', new \Nocarrier\Hal())
// );
// $hal->setResource(
//     'foo',
//     (new \Nocarrier\Hal())
//         ->addResource('bar', new \Nocarrier\Hal(), false)
// );
// $hal
//     ->setResource('foo1', (new \Nocarrier\Hal())->setResource('bar', new \Nocarrier\Hal()))
//     ->setResource('foo2', new \Nocarrier\Hal());
// $hal->setResource(
//     'foo',
//     (new \Nocarrier\Hal())
//         ->setResource('bar1', new \Nocarrier\Hal())
//         ->setResource('bar2', new \Nocarrier\Hal())
// );

// following options DO work
// $hal->setResource('foo', new \Nocarrier\Hal());
// $hal
//     ->setResource('foo1', new \Nocarrier\Hal())
//     ->setResource('foo2', new \Nocarrier\Hal());
// $hal->addResource(
//     'foo',
//     (new \Nocarrier\Hal())->setResource('bar', new \Nocarrier\Hal()),
//     false
// );
// $hal->addResource(
//     'foo',
//     (new \Nocarrier\Hal())->addResource('bar', new \Nocarrier\Hal(), false),
//     false
// );

echo ($hal->asJson(true));
```

Non-working options throw:
`ErrorException in HalJsonRenderer.php line 164: Undefined offset: 0`

Seems to relate to the test `count($embedded) === 1` in https://github.com/blongden/hal/blob/master/src/Nocarrier/HalJsonRenderer.php#L159

I am using current version 0.9.11

**Comment by blongden** [comment] 2015-08-10 11:01
:+1: confirmed - will have a look. Thanks for the report.

**Comment by blongden** [comment] 2015-08-10 14:25
Ok that was harder to track down than I was anticipating - but I think I got it. Should now be fixed on master and will be incorporated into the next release assuming nobody reports any issues.

Thanks for the clear report :)

**Comment by Pittiplatsch** [comment] 2015-08-10 14:45
Thanks a lot for fixing :+1:

**Comment by Blackskyliner** [comment] 2015-08-21 09:41
Well then, if it was fixed, why not close the issue :)

**Comment by blongden** [comment] 2015-08-24 09:12
Because I was sunning myself in Fuerteventura for a couple of weeks ;)

**Closed by blongden** 2015-08-24 09:12 UTC
Labels: bug, fixed
